# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 230)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openfile.setGeometry(QtCore.QRect(10, 10, 75, 20))
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.label_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(100, 10, 231, 20))
        self.label_filepath.setObjectName("label_filepath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 47, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox_students = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_students.setGeometry(QtCore.QRect(40, 40, 69, 22))
        self.comboBox_students.setObjectName("comboBox_students")
        self.comboBox_day = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_day.setGeometry(QtCore.QRect(40, 70, 69, 22))
        self.comboBox_day.setObjectName("comboBox_day")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 301, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_dataname03 = QtWidgets.QLabel(self.groupBox)
        self.label_dataname03.setGeometry(QtCore.QRect(110, 20, 47, 20))
        self.label_dataname03.setObjectName("label_dataname03")
        self.label_dataname05 = QtWidgets.QLabel(self.groupBox)
        self.label_dataname05.setGeometry(QtCore.QRect(210, 20, 47, 20))
        self.label_dataname05.setObjectName("label_dataname05")
        self.label_dataname04 = QtWidgets.QLabel(self.groupBox)
        self.label_dataname04.setGeometry(QtCore.QRect(160, 20, 47, 20))
        self.label_dataname04.setObjectName("label_dataname04")
        self.label_data04 = QtWidgets.QLabel(self.groupBox)
        self.label_data04.setGeometry(QtCore.QRect(160, 50, 47, 20))
        self.label_data04.setObjectName("label_data04")
        self.label_data05 = QtWidgets.QLabel(self.groupBox)
        self.label_data05.setGeometry(QtCore.QRect(210, 50, 47, 20))
        self.label_data05.setObjectName("label_data05")
        self.label_data02 = QtWidgets.QLabel(self.groupBox)
        self.label_data02.setGeometry(QtCore.QRect(60, 50, 47, 20))
        self.label_data02.setObjectName("label_data02")
        self.label_data01 = QtWidgets.QLabel(self.groupBox)
        self.label_data01.setGeometry(QtCore.QRect(10, 50, 47, 20))
        self.label_data01.setObjectName("label_data01")
        self.label_data03 = QtWidgets.QLabel(self.groupBox)
        self.label_data03.setGeometry(QtCore.QRect(110, 50, 47, 20))
        self.label_data03.setObjectName("label_data03")
        self.label_dataname02 = QtWidgets.QLabel(self.groupBox)
        self.label_dataname02.setGeometry(QtCore.QRect(60, 20, 47, 20))
        self.label_dataname02.setObjectName("label_dataname02")
        self.label_dataname01 = QtWidgets.QLabel(self.groupBox)
        self.label_dataname01.setGeometry(QtCore.QRect(10, 20, 47, 20))
        self.label_dataname01.setObjectName("label_dataname01")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_openfile.setText(_translate("MainWindow", "開啟檔案"))
        self.label_filepath.setText(_translate("MainWindow", "---"))
        self.label_2.setText(_translate("MainWindow", "學生"))
        self.label_3.setText(_translate("MainWindow", "天數"))
        self.groupBox.setTitle(_translate("MainWindow", "相關資料"))
        self.label_dataname03.setText(_translate("MainWindow", "---"))
        self.label_dataname05.setText(_translate("MainWindow", "---"))
        self.label_dataname04.setText(_translate("MainWindow", "---"))
        self.label_data04.setText(_translate("MainWindow", "---"))
        self.label_data05.setText(_translate("MainWindow", "---"))
        self.label_data02.setText(_translate("MainWindow", "---"))
        self.label_data01.setText(_translate("MainWindow", "---"))
        self.label_data03.setText(_translate("MainWindow", "---"))
        self.label_dataname02.setText(_translate("MainWindow", "---"))
        self.label_dataname01.setText(_translate("MainWindow", "---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
